### PR TITLE
Fixes #32

### LINKED ISSUE #32: Change Icon name and Icon
**Describe the bug**
In the MainPageNew activity, the Home icon should be replace with Video Icon and name Video
**To Reproduce**
1. Open the App
2. See the error

**Expected behavior**
It should be Video and Video Icon

**Screenshots**

### PR DESCRIPTION
**Pull request by Pranav915**
## Description

Fix #32

1) Changed the Home Icon to Video Icon
2) Changed the name from "Home" to "Videos"
## Checklist:

- [x] I used the Reformat code option in android studio for the files I changed
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The App is running Fine and as Expected In my Emulator or Physical Device
- [x] I have checked my code and corrected any misspellings
- [x] My changes didn't cause any issues for the other functionalities present before.
- [x] This PR is created From a branch which is upto date with the master branch

### CODE REVIEW

**Comment by Amar-2003** [comment]
@Pranav915 , prefect PR description and naming, I will check the code tonight

**Comment by Pranav915** [comment]
> @Pranav915 , prefect PR description and naming, I will check the code tonight

👍👍

**Comment by Amar-2003** [comment]
@Pranav915 , I suspect the app to not to work, is it running fine on physical device or emulator

**Comment by Amar-2003** [comment]
@Pranav915 , Thanks for the PR, Looks good to me

**Review by Amar-2003 — APPROVED** [review]
LGTM !

**Review by ash-100 — APPROVED** [review]

**Comment by Amar-2003** [comment]
Thanks for the PR @Pranav915

**Pull request merged**
