### PR TITLE
Fixes #28 :Changed the download instructions in fragment_book.xml

### LINKED ISSUE #28: Book Download instructions
In the fragment_book.xml a text view should be added at top without interfering with the recycler VIew,
The text view should contain the text "Your Book would be downloaded to the Downloads of your Device" with a small size that the Book Title.

### PR DESCRIPTION
**Pull request by Pranav915**
Fixes #28 
## Description

Fix #28

## Checklist:

- [x] I used the Reformat code option in android studio for the files I changed
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] The App is running Fine and as Expected In my Emulator or Physical Device
- [x] I have checked my code and corrected any misspellings
- [x] My changes didn't cause any issues for the other functionalities present before.
- [x] This PR is created From a branch which is upto date with the master branch

### CODE REVIEW

**Comment by Amar-2003** [comment]
@Pranav915 isn't the app running fine ??

**Comment by Pranav915** [comment]
> @Pranav915 isn't the app running fine ??

no there are many other issues here

**Review by Amar-2003 — APPROVED** [review]
Looks good

**Review by Amar-2003 — CHANGES_REQUESTED** [review]
in the description add Fixes #(issue number) @Pranav915

**Comment by Amar-2003** [comment]
Also in the title add Fixes #(issue number) @Pranav915

**Review by Amar-2003 — APPROVED** [review]
Looks good

**Review by ash-100 — APPROVED** [review]

**Pull request merged**
